# Generated by Django 3.2 on 2025-11-28 07:42

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import franchise.Payment.payment_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=20, unique=True)),
                ('franchise_id', models.CharField(max_length=100)),
                ('batch_details', models.JSONField(default=list)),
                ('specimen_count', models.JSONField(default=list)),
                ('shipment_from', models.CharField(max_length=100)),
                ('shipment_to', models.CharField(max_length=100)),
                ('received', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(default='system', max_length=100)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('short_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('patientname', models.CharField(blank=True, max_length=220, null=True)),
                ('dateOfBirth', models.CharField(blank=True, max_length=220, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('franchise_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('payment_gateway_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise_id', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('franchise_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueShareModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('rules', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('active_from', models.DateField()),
                ('active_till', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('lastmodified_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise_id', models.CharField(max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('testdetails', models.JSONField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('barcode', models.CharField(max_length=100)),
                ('locationId', models.CharField(max_length=100)),
                ('testdetails', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.CharField(default=franchise.Payment.payment_models.generate_wallet_id, max_length=50, primary_key=True, serialize=False)),
                ('franchise_id', models.CharField(max_length=100, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('initial', 'Initial Payment'), ('topup', 'Top Up')], max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wallet_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=20)),
                ('user_notes', models.TextField(blank=True)),
                ('system_notes', models.TextField(blank=True)),
                ('payment_gateway_ref_id', models.CharField(blank=True, max_length=200)),
                ('payment_gateway_txn_id', models.CharField(blank=True, max_length=200)),
                ('payment_gateway_status', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchise.currency')),
                ('payment_gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchise.paymentgateway')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchise.wallet')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('barcode', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('registrationDate', models.DateTimeField(blank=True, null=True)),
                ('registeredBy', models.CharField(blank=True, max_length=100, null=True)),
                ('referredDoctor', models.CharField(blank=True, max_length=100, null=True)),
                ('trf_file_id', models.CharField(blank=True, max_length=100, null=True)),
                ('testdetails', models.JSONField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('discountPercentage', models.CharField(blank=True, max_length=20, null=True)),
                ('discountAmount', models.CharField(blank=True, max_length=20, null=True)),
                ('netAmount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('paymentMode', models.CharField(blank=True, max_length=20, null=True)),
                ('segment', models.CharField(blank=True, max_length=20, null=True)),
                ('franchise_id', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_status', models.CharField(choices=[('Pending', 'Pending'), ('Billed', 'Billed')], default='Pending', max_length=20)),
                ('billed_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='franchise.patient')),
            ],
        ),
        migrations.CreateModel(
            name='FranchiseMonthlyRevenue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monthly_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('franchise_id', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('franchise_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('franchiser_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('wallet_amount_reduced', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('registrations_refs', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10)),
                ('closed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('lastmodified_by', models.CharField(max_length=100)),
                ('revenue_share_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='franchise.revenuesharemodel')),
            ],
            options={
                'unique_together': {('franchise_id', 'year', 'month')},
            },
        ),
    ]
