# Generated by Django 3.2 on 2025-12-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='due_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
