# Generated by Django 3.2 on 2025-12-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0002_billing_due_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='payments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
