# Generated by Django 3.2 on 2026-08-13 11:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0003_billing_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineRequisition',
            fields=[
                ('mr_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('franchise_id', models.CharField(blank=True, max_length=100, null=True)),
                ('items', models.JSONField(blank=True, default=list, null=True)),
                ('Total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(default='Draft', max_length=50)),
                ('approved_by', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('rejected_by', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('rejected_reason', models.TextField(blank=True, default='', null=True)),
                ('rejected_date', models.DateTimeField(blank=True, null=True)),
                ('edited_by', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('edited_reason', models.TextField(blank=True, default='', null=True)),
                ('edited_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(default='system', max_length=100)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
