# Generated by Django 3.2 on 2026-08-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0004_medicinerequisition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicineRequisition',
            new_name='MaterialRequisition',
        ),
    ]
