# Generated by Django 3.2 on 2026-08-14 03:54

from django.db import migrations, models
import franchise.models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0005_rename_medicinerequisition_materialrequisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequisition',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='is_cancelled_by',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='is_cancelled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialrequisition',
            name='items',
            field=franchise.models.SafeJSONField(blank=True, default=list, null=True),
        ),
    ]
