# Generated by Django 3.2 on 2026-08-14 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0006_auto_20260814_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialrequisition',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='materialrequisition',
            name='rejected_date',
        ),
        migrations.RemoveField(
            model_name='materialrequisition',
            name='rejected_reason',
        ),
    ]
