# Generated by Django 3.2 on 2026-08-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0007_auto_20260814_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='remarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
